version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: kratos
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kratos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kratos"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s


  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  keto:
    image: oryd/keto:v0.11.0
    container_name: keto
    command: serve --config /etc/config/keto.yml
    ports:
      - "4466:4466"   # read API
      - "4467:4467"   # admin API
    volumes:
      - ./keto/keto.yml:/etc/config/keto.yml

  keto-bootstrap:
    build: ./keto/bootstrap
    container_name: keto_bootstrap
    environment:
      - KETO_ADMIN_URL=http://keto:4467
    ports:
      - "4000:4000"
    depends_on:
      - keto

  kratos-migrate:
    image: oryd/kratos:v1.1.0
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DSN=postgres://kratos:secret@postgres:5432/kratos?sslmode=disable
    command: migrate sql -e --yes

  kratos:
    image: oryd/kratos:v1.1.0
    container_name: kratos
    depends_on:
      - kratos-migrate
    environment:
      - DSN=postgres://kratos:secret@postgres:5432/kratos?sslmode=disable
    ports:
      - "4433:4433"
      - "4434:4434"
    volumes:
      - ./kratos/kratos.yml:/etc/config/kratos/kratos.yml
      - ./kratos/identity.schema.scansure.json:/etc/config/kratos/identity.schema.scansure.json
    command: serve --dev --config /etc/config/kratos/kratos.yml

  oathkeeper:
    image: oryd/oathkeeper:v0.40.6
    container_name: oathkeeper
    ports:
      - "4455:4455"
      - "4456:4456"
    volumes:
      - ./oathkeeper/oathkeeper.yml:/etc/oathkeeper/config.yml
      - ./oathkeeper/rules:/etc/oathkeeper/rules
    command: ["serve", "-c", "/etc/oathkeeper/config.yml"]
    depends_on:
      - kratos
      - keto

  authz-adapter:
    build: ./authz-adapter
    container_name: authz_adapter
    ports:
      - "7000:7000"
    environment:
      - KETO_READ_URL=http://keto:4466
    depends_on:
      - keto

  envoy:
    image: envoyproxy/envoy:v1.30-latest
    container_name: envoy
    ports:
      - "8080:8080"
    volumes:
      - ./authz-adapter/envoy-config.yaml:/etc/envoy/envoy.yaml:ro
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "info"]
    depends_on:
      - kratos

volumes:
  postgres_data:
