apiVersion: apps/v1
kind: Deployment
metadata:
  name: authz-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authz-adapter
  template:
    metadata:
      labels:
        app: authz-adapter
    spec:
      containers:
        - name: authz-adapter
          image: authz-adapter:latest
